name: iea_ev_prediction
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - pandas==2.0.3
      - scikit-learn==1.3.0
      - mlflow==2.8.1
      - numpy==1.24.3
      - dagshub==0.3.0
      - python-dotenv==1.0.1